// PDF generation for reports — uses the same print-to-PDF approach as pdf.ts

function formatDate(dateStr: string | null | undefined): string {
  if (!dateStr) return "—";
  try {
    return new Date(dateStr + "T00:00:00").toLocaleDateString("en-US", {
      month: "long", day: "numeric", year: "numeric",
    });
  } catch { return dateStr; }
}

function fmt$(val: number | string | null | undefined): string {
  const n = typeof val === "string" ? parseFloat(val) || 0 : (val ?? 0);
  return `$${n.toFixed(2)}`;
}

function monthLabel(monthStr: string): string {
  const [y, m] = monthStr.split("-");
  const date = new Date(parseInt(y), parseInt(m) - 1, 1);
  return date.toLocaleDateString("en-US", { month: "long", year: "numeric" });
}

function truncate(str: string, max: number): string {
  return str.length > max ? str.slice(0, max) + "…" : str;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif;
    font-size: 10pt; color: #1e293b; background: white; line-height: 1.5;
  }
  .page { max-width: 900px; margin: 0 auto; padding: 30px; }
  .header {
    display: flex; align-items: flex-start; justify-content: space-between;
    padding-bottom: 16px; border-bottom: 3px solid #1d4ed8; margin-bottom: 20px;
  }
  .logo-area img { height: 56px; width: auto; }
  .report-info { text-align: right; }
  .report-title { font-size: 13pt; font-weight: 700; color: #1d4ed8; }
  .report-meta { font-size: 9pt; color: #64748b; margin-top: 2px; }
  .filter-bar {
    display: flex; gap: 16px; flex-wrap: wrap;
    padding: 10px 14px; background: #f1f5f9; border-radius: 8px; margin-bottom: 16px;
  }
  .filter-item label { font-size: 7pt; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; font-weight: 600; display: block; }
  .filter-item span { font-size: 9pt; font-weight: 600; color: #1e293b; }
  .summary-grid {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
    gap: 10px; margin-bottom: 16px;
  }
  .summary-card {
    background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;
  }
  .summary-card label { font-size: 7pt; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; font-weight: 600; display: block; }
  .summary-card .val { font-size: 12pt; font-weight: 700; color: #1e293b; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th {
    background: #f1f5f9; text-align: left; padding: 6px 8px;
    font-size: 8pt; text-transform: uppercase; letter-spacing: 0.04em;
    color: #64748b; font-weight: 600; border-bottom: 2px solid #e2e8f0;
  }
  th.right { text-align: right; }
  td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; font-size: 9pt; }
  td.right { text-align: right; }
  td.mono { font-family: monospace; font-size: 8pt; }
  tr.totals { background: #f1f5f9; font-weight: 700; }
  tr.totals td { border-top: 2px solid #e2e8f0; }
  .footer {
    margin-top: 24px; padding-top: 12px; border-top: 1px solid #e2e8f0;
    display: flex; justify-content: space-between; font-size: 8pt; color: #94a3b8;
  }
  .contact-info { margin-bottom: 12px; font-size: 9pt; color: #475569; }
  .issues-list { margin: 0; padding-left: 16px; }
  .issues-list li { font-size: 8pt; color: #475569; }
  @media print { .page { padding: 20px; } }
`;

function buildPage(logoUrl: string, title: string, filters: Array<{ label: string; value: string }>, body: string): string {
  const filterHtml = filters.length > 0
    ? `<div class="filter-bar">${filters.map(f => `<div class="filter-item"><label>${f.label}</label><span>${escapeHtml(f.value)}</span></div>`).join("")}</div>`
    : "";

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"/><title>${escapeHtml(title)}</title><style>${CSS}</style></head>
<body><div class="page">
  <div class="header">
    <div class="logo-area"><img src="${logoUrl}" alt="Fitzpatrick Warranty Service, LLC" /></div>
    <div class="report-info">
      <div class="report-title">${escapeHtml(title)}</div>
      <div class="report-meta">Generated: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</div>
    </div>
  </div>
  ${filterHtml}
  ${body}
  <div class="footer">
    <div>Fitzpatrick Warranty Service, LLC<br/>Utah &amp; Southern Idaho · kevin@fitzpatricksales.com</div>
    <div style="text-align:right">${escapeHtml(title)}<br/>Generated by Fitzpatrick Service Tracker</div>
  </div>
</div></body></html>`;
}

function summaryHtml(items: Array<{ label: string; value: string | number }>): string {
  return `<div class="summary-grid">${items.map(i => `<div class="summary-card"><label>${i.label}</label><div class="val">${i.value}</div></div>`).join("")}</div>`;
}

// ─── Public ─────────────────────────────────────────────────────────────────

export async function generateReportPDF(reportType: string, data: any): Promise<void> {
  const { LOGO_DARK_DATA_URL } = await import("./logo-data");

  let title = "";
  let filters: Array<{ label: string; value: string }> = [];
  let body = "";

  switch (reportType) {
    case "manufacturer-summary": {
      title = "Manufacturer Service Summary";
      filters = [
        { label: "Manufacturer", value: data.manufacturer },
        ...(data.dateFrom ? [{ label: "From", value: formatDate(data.dateFrom) }] : []),
        ...(data.dateTo ? [{ label: "To", value: formatDate(data.dateTo) }] : []),
      ];
      body = summaryHtml([
        { label: "Total Calls", value: data.summary.totalCalls },
        { label: "Unique Models", value: data.summary.uniqueModels },
        { label: "Unique Customers", value: data.summary.uniqueCustomers },
        { label: "Parts Cost", value: fmt$(data.summary.totalPartsCost) },
        { label: "Labor Cost", value: fmt$(data.summary.totalLaborCost) },
        { label: "Claim Amount", value: fmt$(data.summary.totalClaimAmount) },
      ]);
      body += `<table><thead><tr>
        <th>Date</th><th>Customer</th><th>Site</th><th>Model</th><th>Serial</th>
        <th>Status</th><th>Claim</th><th>Claim #</th>
        <th class="right">Parts</th><th class="right">Labor</th><th class="right">Claim $</th>
      </tr></thead><tbody>`;
      for (const c of data.calls) {
        body += `<tr>
          <td>${formatDate(c.callDate)}</td><td>${escapeHtml(c.customerName)}</td><td>${escapeHtml(c.jobSiteName)}</td>
          <td class="mono">${escapeHtml(c.productModel)}</td><td class="mono">${c.productSerial ? escapeHtml(c.productSerial) : "—"}</td>
          <td>${c.status}</td><td>${c.claimStatus}</td><td>${c.claimNumber || "—"}</td>
          <td class="right">${fmt$(c.partsCost)}</td><td class="right">${fmt$(c.laborCost)}</td><td class="right">${fmt$(c.claimAmount)}</td>
        </tr>`;
      }
      body += `<tr class="totals">
        <td colspan="8" style="text-align:right">Totals:</td>
        <td class="right">${fmt$(data.summary.totalPartsCost)}</td>
        <td class="right">${fmt$(data.summary.totalLaborCost)}</td>
        <td class="right">${fmt$(data.summary.totalClaimAmount)}</td>
      </tr></tbody></table>`;
      break;
    }

    case "monthly-expense": {
      title = "Monthly Expense Report";
      filters = [
        ...(data.dateFrom ? [{ label: "From", value: formatDate(data.dateFrom) }] : []),
        ...(data.dateTo ? [{ label: "To", value: formatDate(data.dateTo) }] : []),
      ];
      body = summaryHtml([
        { label: "Total Hours", value: data.summary.totalHours },
        { label: "Total Miles", value: data.summary.totalMiles },
        { label: "Mileage Deduction", value: fmt$(data.summary.totalMileageCost) },
        { label: "Total Costs", value: fmt$(data.summary.totalCosts) },
        { label: "Claim Amount", value: fmt$(data.summary.totalClaimAmount) },
        { label: "Net", value: fmt$(data.summary.net) },
      ]);
      body += `<table><thead><tr>
        <th>Month</th><th class="right">Calls</th><th class="right">Hours</th><th class="right">Miles</th>
        <th class="right">Mileage $</th><th class="right">Parts</th><th class="right">Labor</th>
        <th class="right">Other</th><th class="right">Total</th><th class="right">Claim $</th>
      </tr></thead><tbody>`;
      for (const m of data.months) {
        body += `<tr>
          <td>${monthLabel(m.month)}</td><td class="right">${m.calls}</td>
          <td class="right">${m.hours}</td><td class="right">${m.miles}</td>
          <td class="right">${fmt$(m.mileageCost)}</td><td class="right">${fmt$(m.partsCost)}</td>
          <td class="right">${fmt$(m.laborCost)}</td><td class="right">${fmt$(m.otherCost)}</td>
          <td class="right">${fmt$(m.totalCosts)}</td><td class="right">${fmt$(m.claimAmount)}</td>
        </tr>`;
      }
      body += `<tr class="totals">
        <td>Grand Total</td>
        <td class="right">${data.months.reduce((s: number, m: any) => s + m.calls, 0)}</td>
        <td class="right">${data.summary.totalHours}</td><td class="right">${data.summary.totalMiles}</td>
        <td class="right">${fmt$(data.summary.totalMileageCost)}</td><td class="right">${fmt$(data.summary.totalPartsCost)}</td>
        <td class="right">${fmt$(data.summary.totalLaborCost)}</td><td class="right">${fmt$(data.summary.totalOtherCost)}</td>
        <td class="right">${fmt$(data.summary.totalCosts)}</td><td class="right">${fmt$(data.summary.totalClaimAmount)}</td>
      </tr></tbody></table>`;
      break;
    }

    case "customer-history": {
      title = `Customer History — ${data.customer}`;
      filters = [
        ...(data.dateFrom ? [{ label: "From", value: formatDate(data.dateFrom) }] : []),
        ...(data.dateTo ? [{ label: "To", value: formatDate(data.dateTo) }] : []),
      ];
      if (data.contact) {
        const c = data.contact;
        const parts = [c.address, c.city, c.state].filter(Boolean).join(", ");
        body += `<div class="contact-info">`;
        if (parts) body += `<div>${escapeHtml(parts)}</div>`;
        if (c.phone) body += `<div>Phone: ${escapeHtml(c.phone)}</div>`;
        if (c.email) body += `<div>Email: ${escapeHtml(c.email)}</div>`;
        body += `</div>`;
      }
      body += summaryHtml([
        { label: "Total Calls", value: data.summary.totalCalls },
        { label: "Parts Cost", value: fmt$(data.summary.totalPartsCost) },
        { label: "Labor Cost", value: fmt$(data.summary.totalLaborCost) },
        { label: "Claim Amount", value: fmt$(data.summary.totalClaimAmount) },
      ]);
      body += `<table><thead><tr>
        <th>Date</th><th>Site</th><th>Manufacturer</th><th>Model</th><th>Serial</th>
        <th>Issue</th><th>Status</th><th>Claim</th><th class="right">Claim $</th>
      </tr></thead><tbody>`;
      for (const c of data.calls) {
        body += `<tr>
          <td>${formatDate(c.callDate)}</td><td>${escapeHtml(c.jobSiteName)}</td>
          <td>${escapeHtml(c.manufacturer)}</td><td class="mono">${escapeHtml(c.productModel)}</td>
          <td class="mono">${c.productSerial ? escapeHtml(c.productSerial) : "—"}</td>
          <td>${escapeHtml(truncate(c.issueDescription, 80))}</td>
          <td>${c.status}</td><td>${c.claimStatus}</td><td class="right">${fmt$(c.claimAmount)}</td>
        </tr>`;
      }
      body += `</tbody></table>`;
      break;
    }

    case "claim-status": {
      title = "Claim Status Report";
      filters = [
        ...(data.manufacturer ? [{ label: "Manufacturer", value: data.manufacturer }] : []),
        ...(data.dateFrom ? [{ label: "From", value: formatDate(data.dateFrom) }] : []),
        ...(data.dateTo ? [{ label: "To", value: formatDate(data.dateTo) }] : []),
      ];
      // Status summary
      const statusItems = Object.entries(data.statusCounts as Record<string, { count: number; amount: number }>).map(([status, info]) => ({
        label: status,
        value: `${info.count} calls · ${fmt$(info.amount)}`,
      }));
      body = summaryHtml(statusItems);
      body += `<table><thead><tr>
        <th>Call #</th><th>Date</th><th>Customer</th><th>Manufacturer</th><th>Model</th>
        <th>Claim #</th><th>Status</th><th class="right">Amount</th><th class="right">Days</th>
      </tr></thead><tbody>`;
      for (const c of data.calls) {
        body += `<tr>
          <td>#${c.id}</td><td>${formatDate(c.callDate)}</td><td>${escapeHtml(c.customerName)}</td>
          <td>${escapeHtml(c.manufacturer)}</td><td class="mono">${escapeHtml(c.productModel)}</td>
          <td>${c.claimNumber || "—"}</td><td>${c.claimStatus}</td>
          <td class="right">${fmt$(c.claimAmount)}</td><td class="right">${c.daysPending}</td>
        </tr>`;
      }
      body += `</tbody></table>`;
      break;
    }

    case "product-failure": {
      title = "Product Failure Report";
      filters = [
        ...(data.manufacturer ? [{ label: "Manufacturer", value: data.manufacturer }] : []),
        ...(data.dateFrom ? [{ label: "From", value: formatDate(data.dateFrom) }] : []),
        ...(data.dateTo ? [{ label: "To", value: formatDate(data.dateTo) }] : []),
        { label: "Min Occurrences", value: String(data.minCount) },
      ];
      body = `<table><thead><tr>
        <th>Manufacturer</th><th>Model</th><th class="right">Calls</th><th class="right">Serials</th>
        <th class="right">Customers</th><th>Last Service</th><th>Common Issues</th>
      </tr></thead><tbody>`;
      for (const m of data.models) {
        const issuesHtml = m.issues.length > 0
          ? `<ul class="issues-list">${m.issues.slice(0, 3).map((iss: string) => `<li>${escapeHtml(truncate(iss, 80))}</li>`).join("")}${m.issues.length > 3 ? `<li>+${m.issues.length - 3} more</li>` : ""}</ul>`
          : "—";
        body += `<tr>
          <td>${escapeHtml(m.manufacturer)}</td><td class="mono">${escapeHtml(m.model)}</td>
          <td class="right" style="font-weight:700">${m.count}</td><td class="right">${m.uniqueSerials}</td>
          <td class="right">${m.uniqueCustomers}</td><td>${formatDate(m.lastServiceDate)}</td>
          <td>${issuesHtml}</td>
        </tr>`;
      }
      body += `</tbody></table>`;
      break;
    }
  }

  const html = buildPage(LOGO_DARK_DATA_URL, title, filters, body);

  const win = window.open("", "_blank");
  if (!win) {
    throw new Error("Popup blocked. Please allow popups for this site.");
  }
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 500);
}
